[platformio]
default_envs = blynk

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags =
  -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps =
  mathieucarbou/AsyncTCP @ 3.2.4
  mathieucarbou/ESPAsyncWebServer @ 3.1.5
  ayushsharma82/ElegantOTA @ 3.1.6
  blynkkk/Blynk@1.3.2

; MÔI TRƯỜNG 1: XÂY DỰNG FILE BIN CHO BLYNK
[env:blynk]
build_flags =
  ${env.build_flags}
  -D USE_BLYNK

; MÔI TRƯỜNG 2: XÂY DỰNG FILE BIN CHO ESP RAINMAKER
[env:rainmaker]
build_flags =
  ${env.build_flags}
  -D USE_RAINMAKER
board_build.partitions = partitions_rmaker.csv
lib_deps =
  mathieucarbou/AsyncTCP @ 3.2.4
  mathieucarbou/ESPAsyncWebServer @ 3.1.5
  ayushsharma82/ElegantOTA @ 3.1.6
; RainMaker đã được tích hợp sẵn trong core ESP32 (không cần tải thêm lib)
